# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumName', models.CharField(max_length=100)),
                ('AlbumCover', models.FileField(null=True, upload_to='Genre/Artist/Album/')),
                ('YearReleased', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Born', models.DateTimeField(auto_now=True)),
                ('Bio', models.TextField()),
                ('Artist', models.FileField(null=True, upload_to='Genre/Artist/')),
            ],
        ),
        migrations.CreateModel(
            name='GenreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SongType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongName', models.CharField(max_length=100)),
                ('Song', models.FileField(null=True, upload_to='Genre/Artist/Album/Song/')),
                ('AlbumNames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlbumTypes', to='web_app.AlbumType')),
            ],
        ),
        migrations.AddField(
            model_name='artisttype',
            name='GenreType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GenreTypes', to='web_app.GenreType'),
        ),
        migrations.AddField(
            model_name='artisttype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albumtype',
            name='ArtistName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArtistTypes', to='web_app.ArtistType'),
        ),
    ]
