# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisttype',
            name='DateJoined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songtype',
            name='ReleaseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
