# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_blogposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisttype',
            name='Artist',
        ),
        migrations.AddField(
            model_name='artisttype',
            name='ArtistPictures',
            field=models.FileField(null=True, upload_to='Genre/Artist/'),
        ),
        migrations.AlterField(
            model_name='albumtype',
            name='YearReleased',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='Born',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
