# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20180808_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtype',
            name='SongImage',
            field=models.FileField(null=True, upload_to='Genre/Artist/Album/Song/Image'),
        ),
    ]
