# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_songtype_songimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtype',
            name='ArtistNames',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='ArtistTypes', to='web_app.AlbumType'),
            preserve_default=False,
        ),
    ]
