# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-07 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_remove_songtype_artistnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('VotedSong', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
